framework.nav("react.workspace", "React", "/wiz/admin/react.workspace", r'^/wiz/admin/react.workspace')
framework.subnav("react.workspace", "route", "Route", "/wiz/admin/react.workspace/routes", r'^/wiz/admin/react.workspace/routes')
framework.subnav("react.workspace", "app", "App", "/wiz/admin/react.workspace/apps", r'^/wiz/admin/react.workspace/apps')
framework.subnav("react.workspace", "controller", "Controller", "/wiz/admin/react.workspace/ctrls", r'^/wiz/admin/react.workspace/ctrls')
framework.subnav("react.workspace", "model", "Model", "/wiz/admin/react.workspace/models", r'^/wiz/admin/react.workspace/models')
framework.subnav("react.workspace", "theme", "Theme", "/wiz/admin/react.workspace/themes", r'^/wiz/admin/react.workspace/themes')
framework.subnav("react.workspace", "resource", "Resource", "/wiz/admin/react.workspace/res", r'^/wiz/admin/react.workspace/res')
framework.subnav("react.workspace", "config", "Config", "/wiz/admin/react.workspace/config", r'^/wiz/admin/react.workspace/config')